=== Aim4dStars/work/nextgenx/src/main/resources/com/bt/nextgen/api/draftaccount/schemas/v1/accountApplicationSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "javaType" : "com.bt.nextgen.api.draftaccount.schemas.v1.OnboardingApplicationFormData",
  "type": "object",
  "properties": {
    "version": {
      "type": "string",
      "description": "this is the application Account JSON Schema Version number supported by client & server (http://semver.org/)",
      "pattern": "^[1-99]{1}.[0-99]{1}.[0-99]{1}$"
    },
    "parentProductName" : {
      "type": "string",
      "description": "This field contains the parent product name for this account."
    },
    "accountType": {
      "$ref": "base/accountTypeEnum.json"
    },
    "approvalType": {
      "$ref": "base/approvalTypeEnum.json",
      "description": "This field indicates the type of approval method selected for this account."
    },
    "trustType": {
      "$ref": "base/trustTypeEnum.json"
    },
    "trustdetails": {
      "type": "object",
      "$ref": "trust/trustdetailsSchema.json"
    },
    "pensioneligibility": {
      "type": "object",
      "$ref": "pensioneligibility/pensionEligibilitySchema.json",
      "description": "This schema is used for the Super Pension eligibility applicable only for super pension account."
     },
    "smsfdetails": {
      "type": "object",
      "$ref": "smsf/smsfdetailsSchema.json"
    },
    "directors": {
      "type": "array",
      "items": {
        "$ref" : "customer/customerSchema.json"
      }
    },
    "trustees": {
      "type": "array",
      "items": {
        "$ref" : "customer/customerSchema.json"
      }
    },
    "investors": {
      "type": "array",
      "items": {
        "$ref" : "customer/customerSchema.json"
      }
    },
    "companydetails": {
      "$ref": "company/companydetailsSchema.json"
    },
    "shareholderandmembers": {
      "type": "object",
      "$ref": "company/shareholderandmembersSchema.json"
    },
    "accountsettings": {
      "$ref": "accountsettings/accountsettingsSchema.json"
    },
    "companytrustee": {
      "$ref": "company/companydetailsSchema.json"
    },
    "linkedaccounts": {
      "$ref": "linkedaccounts/linkedAccountsApplicationSchema.json"
    },
    "fees": {
      "$ref": "fees/feesSchema.json"
    }
  },
  "additionalProperties": false,
  "allOf":[
    {
      "required": [
        "version",
        "accountType",
        "accountsettings",
        "linkedaccounts"
      ],
      "description": "required for all account types"
    },
    {
      "oneOf":[
        {
          "required": [ "investors" ],
          "description": "required only for individual account"
        },
        {
          "required": [ "companydetails", "directors", "shareholderandmembers" ],
          "description": "required only for company account"
        },
        {
          "required": [ "trustdetails", "trustees", "trustType", "shareholderandmembers" ],
          "description": "required only for Individual Trust account"
        },
        {
          "required": [ "trustdetails", "companytrustee", "trustType", "shareholderandmembers" ],
          "description": "required only for Company Trust account"
        },
        {
          "required": [ "smsfdetails", "trustees", "shareholderandmembers" ],
          "description": "required only for SMSF Individual account"
        },
        {
          "required": [ "smsfdetails", "companytrustee", "directors", "shareholderandmembers" ],
          "description": "required only for SMSF Corporate account"
        }
      ]
    }
  ]
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/builder/v3_JsonSchema/individual_existingPanoramaWithCRS.json
{
"version": "1.0.0",
"parentProductName": "BT Panorama Investments",
"accountType": "individual",
"investors": [
  {
    "emails": [
      {
        "email": "gob@bluth.com",
        "preferred": false,
        "emailType": "Primary"
      }
    ],
    "gcmId": "217293604",
    "key": {
      "clientId": "539CD9D6337CA7D40AA8EA5045D3F5A834DE2E3EA0A80A7A"
    },
    "personRoles": [
      "Owner"
    ],
    "phones": [
      {
        "preferred": true,
        "number": "0437275468",
        "phoneType": "Primary",
        "type": "Phone",
        "label": "Mobile - primary"
      }
    ],
    "gcmTitleLabel": "Mr",
    "cisId": "48813020036",
    "userName": "Taylor",
    "idVerified": true,
    "taxdetails": {
      "ausTaxDetails": {
        "tfn": {
          "valid": false
        },
        "taxOption": {
          "valid": true,
          "value": "Exemption Reason provided"
        },
        "isTaxCountryAus": {
          "valid": true,
          "value": true
        },
        "exemptionReason": {
          "valid": true,
          "value": "norfolk_island_res"
        }
      },
      "isOverseasTaxRes": {
        "valid": true,
        "value": true
      },
      "overseasTaxDetails": [
        {
          "tin": {
            "valid": true
          },
          "tinOption": {
            "valid": true,
            "value": "Exemption Reason provided"
          },
          "overseasTaxCountry": {
            "valid": true,
            "value": "NZ"
          },
          "tinExemptionReason": {
            "valid": true,
            "value": "btfg$tin_never_iss"
          }
        }
      ]
    },
    "isDuplicate": false,
    "registered": true,
    "tfnProvided": false,
    "investorType": "INDIVIDUAL",
    "displayTaxOptions": true,
    "title": "Mr",
    "firstname": "Gob",
    "lastname": "Bluth",
    "dateofbirth": "13 Jan 1990",
    "gender": "Male",
    "mobile": {
      "value": "0437275468"
    },
    "email": {
      "value": "gob@bluth.com"
    },
    "isvalid": true,
    "accountType": "individual",
    "resaddress": {
      "stateAbbr": "NSW",
      "domicile": true,
      "countryCode": "2061",
      "internationalAddress": false,
      "mailingAddress": false,
      "standardAddressFormat": false,
      "addressType": "Postal",
      "streetNumber": "135-151",
      "streetName": "Clarence",
      "streetType": "Street",
      "suburb": "Sydney",
      "state": "New South Wales",
      "postcode": "2000",
      "country": "Australia",
      "existingAddressList": []
    },
    "postaladdress": {
      "stateAbbr": "NSW",
      "domicile": false,
      "countryCode": "2061",
      "internationalAddress": false,
      "mailingAddress": true,
      "standardAddressFormat": false,
      "addressType": "Postal",
      "streetNumber": "135-151",
      "streetName": "Clarence",
      "streetType": "Street",
      "suburb": "Sydney",
      "state": "New South Wales",
      "postcode": "2000",
      "country": "Australia",
      "existingAddressList": []
    },
    "resiCountryforTax": "New Zealand",
    "tfnExemptId": "99",
    "saTfnExemptId": "4",
    "exemptionReason": "No exemption",
    "isForeignRegistered": "Y"
  }
],
"accountsettings": {
  "professionalspayment": "linkedaccountsonly",
  "investorAccountSettings": [
    {
      "paymentSetting": "nopayments",
      "hasRoles": false,
      "hasApprovers": false
    }
  ],
  "primarycontact": 0,
  "adviserName": "Richard Peterson",
  "adviserLocation": "New South Wales",
  "sourceoffunds": "Business income/earnings",
  "powerofattorney": false
},
"linkedaccounts": {
  "primaryLinkedAccount": {
    "accountname": "test",
    "bsb": "062005",
    "accountnumber": "123456",
    "nickname": "esrf",
    "directdebitamount": "4234.00",
    "bsbValidationResultVal": true
  },
  "otherLinkedAccount": []
},
"fees": {
  "estamount": "0.00",
  "ongoingFees": {
    "feesComponent": [],
    "type": "Ongoing advice fee"
  },
  "licenseeFees": {
    "feesComponent": [
      {
        "label": "Percentage fee component",
        "listedSecurities": "2.00",
        "managedFund": "1.00",
        "managedPortfolio": "0.00",
        "cash": "0.00",
        "termDeposit": "0.00",
        "slidingScaleFeeTier": [],
        "valid": true
      }
    ],
    "type": "Licensee advice fee"
  }
}
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/model/individual-new-4-empty.json
{
  "accountType": "individual",
  "version": "1.0.0",
  "investors": [{
    "displayTaxOptions": true,
    "cismandatory": true,
    "title": "",
    "firstname": "",
    "middlename": "",
    "lastname": "",
    "preferredname": "",
    "formername": "",
    "gender": "",
    "mobile": {
      "value": ""
    },
    "email": {
      "value": ""
    },
    "preferredcontact": "",
    "isvalid": false,

    "accountType": "individual",
    "alternatename": "",
    "identitydocument": {},
    "resaddress": {
      "componentised": false,
      "country": "AU",
      "addressType": "residential",
      "sameasaddress": "0",
      "valid": false
    },
    "postaladdress": {
      "componentised": false,
      "country": "AU",
      "addressType": "postal",
      "sameasaddress": "0",
      "valid": false
    },
    "taxcountry": "AU",
    "taxoption": ""
  }],
  "accountsettings": {
    "investorAccountSettings": [{
      "hasRoles": false,
      "hasApprovers": false
    }],
    "primarycontact": 0,
    "adviserName": "Paul Folks",
    "adviserLocation": "South Australia"
  },
  "linkedaccounts": {
    "primaryLinkedAccount": {
    },
    "otherLinkedAccount": []
  },
  "fees": {
    "estamount": "0.00",
    "feeTabEnabled":true,
    "ongoingFees": {
      "feesComponent": [],
      "type": "Ongoing advice fee"
    },
    "licenseeFees": {
      "feesComponent": [],
      "type": "Licensee advice fee"
    }
  }
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/model/smsf-new-corporate-2.json
{
  "accountType": "newCorporateSMSF",
  "approvalType": "online",
  "version": "1.0.0",
  "smsfdetails": {
    "smsfabn": "",
    "regdate": "",
    "registeredforgst": "yes",
    "industry": {
      "industry": "7412",
      "anzsiccode": "7412",
      "ucmcode": "SIC 0360"
    },
    "wealthsource": "Additional Sources",
    "additionalsourceofwealth": "Money Laundering",
    "smsfname": "The New Corporate SMSF",
    "smsfaddress": {
      "componentised": true,
      "unitNumber": "",
      "streetNumber": "28",
      "streetName": "West",
      "streetType": "STREET",
      "suburb": "NORTH SYDNEY",
      "state": "NSW",
      "postcode": "2060",
      "country": "AU",
      "verified": true,
      "addressType": "residential",
      "existingAddressList": [
        {
          "componentised": true,
          "unitNumber": "",
          "streetNumber": "28",
          "streetName": "West",
          "streetType": "STREET",
          "suburb": "NORTH SYDNEY",
          "state": "NSW",
          "postcode": "2060",
          "country": "AU",
          "verified": true,
          "confirmed": true,
          "valid": true,
          "sameasaddress": "0",
          "addressType": "residential",
          "id": "845379"
        }
      ],
      "sameasaddress": "0",
      "confirmed": false,
      "valid": true
    },
    "registrationstate": "NSW"
  },
  "companytrustee": {
    "companyname": "The Trustee Company",
    "asicregisteredname": "dsdssds",
    "industry": {
      "industry": "7412",
      "anzsiccode": "7412",
      "ucmcode": "SIC 0360"
    },
    "companyoffice": {
      "componentised": true,
      "unitNumber": "",
      "streetNumber": "28",
      "streetName": "West",
      "streetType": "STREET",
      "suburb": "NORTH SYDNEY",
      "state": "NSW",
      "postcode": "2060",
      "country": "AU",
      "verified": true,
      "addressType": "residential",
      "existingAddressList": [
        {
          "componentised": true,
          "unitNumber": "",
          "streetNumber": "28",
          "streetName": "West",
          "streetType": "STREET",
          "suburb": "NORTH SYDNEY",
          "state": "NSW",
          "postcode": "2060",
          "country": "AU",
          "verified": true,
          "confirmed": true,
          "valid": true,
          "sameasaddress": "0",
          "addressType": "residential",
          "id": "476281"
        }
      ],
      "sameasaddress": "0",
      "confirmed": true,
      "valid": true
    },
    "placeofbusiness": {
      "componentised": true,
      "unitNumber": "",
      "streetNumber": "28",
      "streetName": "West",
      "streetType": "STREET",
      "suburb": "NORTH SYDNEY",
      "state": "NSW",
      "postcode": "2060",
      "country": "AU",
      "verified": true,
      "addressType": "residential",
      "existingAddressList": [
        {
          "componentised": true,
          "unitNumber": "",
          "streetNumber": "28",
          "streetName": "West",
          "streetType": "STREET",
          "suburb": "NORTH SYDNEY",
          "state": "NSW",
          "postcode": "2060",
          "country": "AU",
          "verified": true,
          "confirmed": true,
          "valid": true,
          "sameasaddress": "0",
          "addressType": "residential",
          "id": "179656"
        }
      ],
      "sameasaddress": "0",
      "confirmed": false,
      "valid": true
    }
  },
  "directors": [
    {
      "isvalid": true,
      "key": {
        "clientId": "4E9F4BF67C010872107B51D427BACE10B33A0FA404360F2D"
      },
      "userName": "",
      "emails": [
        {
          "email": "TestCoreSMSFfivetwosixteen@email.com",
          "preferred": false,
          "emailType": "Primary"
        }
      ],
      "phones": [
        {
          "preferred": true,
          "number": "0425462316",
          "phoneType": "Primary",
          "type": "Phone",
          "label": "Mobile - primary"
        }
      ],
      "idVerified": true,
      "registered": true,
      "tfnProvided": true,
      "exemptionreason": "norfolk_island_res",
      "personRoles": [
        "Owner"
      ],
      "gcmId": "237329650",
      "investorType": "INDIVIDUAL",
      "tfnExemptId": "99",
      "cisId": "20444910070",
      "title": "Mr",
      "gcmTitleLabel": "Mr",
      "gender": "Male",
      "accountType": "newCorporateSMSF",
      "firstname": "Testcoresmsffivetwosixteen",
      "formername": "Ssdsdsdd",
      "lastname": "First",
      "preferredname": "Prefname",
      "dateofbirth": "01 May 1986",
      "mobile": {
        "value": "0425462316"
      },
      "email": {
        "value": "TestCoreSMSFfivetwosixteen@email.com"
      },
      "isDuplicate": true,
      "eligibletrustee": "Confirmed",
      "placeofbirth": {
        "placeofbirthcountry": "AL",
        "placeofbirthinternationalcity": "AAAAA",
        "placeofbirthinternationalprovince": "AAAA"
      }
    },
    {
      "isvalid": false,
      "key": {
        "clientId": "C4C7EB6CB26186561F4A21ED048C69B6B0E61BFD17B480F3"
      },
      "userName": "",
      "emails": [
        {
          "email": "mail@mail.com",
          "preferred": false,
          "emailType": "Primary"
        }
      ],
      "phones": [
        {
          "preferred": true,
          "number": "0412345678",
          "phoneType": "Primary",
          "type": "Phone",
          "label": "Mobile - primary"
        }
      ],
      "idVerified": true,
      "registered": true,
      "tfnProvided": true,
      "exemptionreason": "norfolk_island_res",
      "personRoles": [
        "Owner"
      ],
      "gcmId": "237329696",
      "investorType": "INDIVIDUAL",
      "tfnExemptId": "99",
      "cisId": "99829910033",
      "title": "Mr",
      "gcmTitleLabel": "Mr",
      "gender": "Male",
      "accountType": "newCorporateSMSF",
      "firstname": "Testoneuser",
      "formername": "TestFormerNAme",
      "lastname": "Last",
      "preferredname": "Perff",
      "dateofbirth": "09 Aug 1990",
      "mobile": {
        "value": "0412345678"
      },
      "email": {
        "value": "mail@mail.com"
      },
      "isDuplicate": true,
      "placeofbirth": {
        "placeofbirthcountry": "AU",
        "placeofbirthsuburb": "AAAAAAA",
        "placeofbirthstate": "NSW"
      }
    }
  ],
  "accountsettings": {
    "professionalspayment": "allpayments",
    "investorAccountSettings": [
      {
        "isApprover": "true",
        "paymentSetting": "nopayments",
        "hasRoles": false,
        "hasApprovers": true
      },
      {
        "isApprover": "true",
        "paymentSetting": "linkedaccountsonly",
        "hasRoles": false,
        "hasApprovers": true
      }
    ],
    "primarycontact": 0,
    "adviserName": "Michelle Hicks",
    "adviserLocation": "South Australia",
    "sourceoffunds": "Business profits"
  },
  "shareholderandmembers": {
    "needsShareholder": true,
    "needsMember": true,
    "needsBeneficiary": false,
    "needsBeneficialOwner": false,
    "accountType": "newCorporateSMSF",
    "investorsWithRoles": [
      {
        "isMember": "no",
        "isShareholder": "yes",
        "needsShareholder": true,
        "needsMember": true,
        "needsBeneficiary": false,
        "needsBeneficialOwner": false
      },
      {
        "isMember": "yes",
        "isShareholder": "yes",
        "needsShareholder": true,
        "needsMember": true,
        "needsBeneficiary": false,
        "needsBeneficialOwner": false
      }
    ],
    "additionalShareHoldersAndMembers": []
  },
  "linkedaccounts": {
    "primaryLinkedAccount": {
      "accountname": "sdsds",
      "bsb": "32323",
      "accountnumber": "232323",
      "nickname": "32323",
      "directdebitamount": "232.00"
    },
    "otherLinkedAccount": []
  },
  "fees": {
    "estamount": "0.00",
    "ongoingFees": {
      "feesComponent": [],
      "type": "Ongoing advice fee"
    },
    "licenseeFees": {
      "feesComponent": [],
      "type": "Licensee advice fee"
    }
  }
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/service/client_application_individualtrust_family_cma_form_data.json
{
         "version":"1.0.0",
         "accountType":"individualTrust",
         "trustType":"family",
         "trustdetails":{
            "trustname":"test",
            "businessname":"test",
            "regdate":"11/11/1990",
            "registrationstate":"NSW",
            "registeredforgst":"yes",
            "settloroftrust":"organisation",
            "wealthsource":"Business profits",
            "abn":"",
            "trusttype":"family",
            "organisationName":"test",
            "industry":{
               "anzsiccode":"7412",
               "industry":"7412",
               "ucmcode":"SIC 0360"
            },
            "addressv2":{
               "addressType":"residential",
               "country":"AU",
               "sameasaddress":"0",
               "valid":true,
               "DisplayText":"78 Crimea Street, PARRAMATTA  NSW  2150",
               "AddressIdentifier":"0DOAUEHwjgBwAAAAAIAgEAAAAAmhq80AAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
               "existingAddressList":[
                  {
                     "country":"AU",
                     "sameasaddress":"0",
                     "valid":true,
                     "DisplayText":"78 Crimea Street, PARRAMATTA  NSW  2150",
                     "AddressIdentifier":"0DOAUEHwjgBwAAAAAIAgEAAAAAmhq80AAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
                     "existingAddressList":[

                     ]
                  }
               ]
            },
            "trustverification":{
               "identitydocument":"trustdeed",
               "trustdeed":{
                  "fullname":"fdfdgfdgfdg",
                  "documentdate":"11/11/2016",
                  "verifiedfrom":"certifiedcopy"
               }
            },
            "taxdetails":{
               "ausTaxDetails":{
                  "tfn":{
                     "valid":false
                  },
                  "taxOption":{
                     "valid":true,
                     "value":"Tax File Number or exemption not provided"
                  },
                  "isTaxCountryAus":{
                     "valid":true,
                     "value":true
                  },
                  "exemptionReason":{
                     "valid":true
                  }
               },
               "isOverseasTaxRes":{
                  "valid":true,
                  "value":false
               },
               "overseasTaxDetails":[

               ]
            },
            "personalinvestmententity":true
         },
         "trustees":[
            {
               "emails":[

               ],
               "personRoles":[

               ],
               "phones":[

               ],
               "taxdetails":{
                  "ausTaxDetails":{
                     "isTaxCountryAus":{
                        "valid":true,
                        "value":true
                     }
                  },
                  "isOverseasTaxRes":{
                     "valid":true,
                     "value":false
                  },
                  "overseasTaxDetails":[

                  ]
               },
               "title":"MR",
               "firstname":"test",
               "middlename":"",
               "lastname":"one",
               "preferredname":"",
               "formername":"",
               "dateofbirth":"11/11/1988",
               "gender":"male",
               "mobile":{
                  "value":"0451223442"
               },
               "email":{
                  "value":"test@test.com"
               },
               "preferredcontact":"email",
               "isvalid":true,
               "alternatename":"",
               "accountType":"individualTrust",
               "identitydocument":{
                  "internationaldocuments":{
                     "nationalid":{
                        "documentIssuer":"DZ",
                        "issueDate":"23/02/2017",
                        "documentNumber":"54645645645",
                        "verificationSource":"certifiedcopy",
                        "englishTranslation":"notapplicable"
                     },
                     "valid":true
                  }
               },
               "resaddressv2":{
                  "addressType":"residential",
                  "country":"AU",
                  "sameasaddress":"0DOAUEHwjgBwAAAAAIAgEAAAAAmhq80AAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
                  "valid":true,
                  "DisplayText":"78 Crimea Street, PARRAMATTA  NSW  2150",
                  "AddressIdentifier":"0DOAUEHwjgBwAAAAAIAgEAAAAAmhq80AAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
                  "existingAddressList":[
                     {
                        "country":"AU",
                        "sameasaddress":"0",
                        "valid":true,
                        "DisplayText":"78 Crimea Street, PARRAMATTA  NSW  2150",
                        "AddressIdentifier":"0DOAUEHwjgBwAAAAAIAgEAAAAAmhq80AAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
                        "existingAddressList":[

                        ]
                     }
                  ]
               },
               "postaladdressv2":{
                  "addressType":"postal",
                  "country":"AU",
                  "sameasaddress":"0DOAUEHwjgBwAAAAAIAgEAAAAAmhq80AAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
                  "valid":true,
                  "DisplayText":"78 Crimea Street, PARRAMATTA  NSW  2150",
                  "AddressIdentifier":"0DOAUEHwjgBwAAAAAIAgEAAAAAmhq80AAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
                  "existingAddressList":[
                     {
                        "country":"AU",
                        "sameasaddress":"0",
                        "valid":true,
                        "DisplayText":"78 Crimea Street, PARRAMATTA  NSW  2150",
                        "AddressIdentifier":"0DOAUEHwjgBwAAAAAIAgEAAAAAmhq80AAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
                        "existingAddressList":[

                        ]
                     }
                  ]
               },
               "sameasresaddress":"true"
            }
         ],
         "shareholderandmembers":{
            "needsShareholder":false,
            "needsMember":false,
            "needsBeneficiary":true,
            "accountType":"individualTrust",
            "investorsWithRoles":[
               {
                  "needsShareholder":false,
                  "needsMember":false,
                  "needsBeneficiary":true
               }
            ],
            "additionalShareHoldersAndMembers":[

            ]
         },
         "accountsettings":{
            "professionalspayment":"linkedaccountsonly",
            "investorAccountSettings":[
               {
                  "paymentSetting":"linkedaccountsonly",
                  "hasRoles":false,
                  "hasApprovers":true,
                  "isApprover":"true"
               }
            ],
            "primarycontact":0,
            "adviserName":"Edward Revis",
            "adviserLocation":"New South Wales",
            "sourceoffunds":"Business income/earnings",
            "powerofattorney":false
         },
         "linkedaccounts":{
            "primaryLinkedAccount":{

            },
            "otherLinkedAccount":[

            ]
         },
         "fees":{
            "estamount":"0.00",
            "ongoingFees":{
               "feesComponent":[

               ],
               "type":"Ongoing advice fee"
            }
         }
      }
