=== Aim4dStars/work/nextgenx/src/main/resources/com/bt/nextgen/api/draftaccount/schemas/v1/accountApplicationSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "javaType" : "com.bt.nextgen.api.draftaccount.schemas.v1.OnboardingApplicationFormData",
  "type": "object",
  "properties": {
    "version": {
      "type": "string",
      "description": "this is the application Account JSON Schema Version number supported by client & server (http://semver.org/)",
      "pattern": "^[1-99]{1}.[0-99]{1}.[0-99]{1}$"
    },
    "parentProductName" : {
      "type": "string",
      "description": "This field contains the parent product name for this account."
    },
    "accountType": {
      "$ref": "base/accountTypeEnum.json"
    },
    "approvalType": {
      "$ref": "base/approvalTypeEnum.json",
      "description": "This field indicates the type of approval method selected for this account."
    },
    "trustType": {
      "$ref": "base/trustTypeEnum.json"
    },
    "trustdetails": {
      "type": "object",
      "$ref": "trust/trustdetailsSchema.json"
    },
    "pensioneligibility": {
      "type": "object",
      "$ref": "pensioneligibility/pensionEligibilitySchema.json",
      "description": "This schema is used for the Super Pension eligibility applicable only for super pension account."
     },
    "smsfdetails": {
      "type": "object",
      "$ref": "smsf/smsfdetailsSchema.json"
    },
    "directors": {
      "type": "array",
      "items": {
        "$ref" : "customer/customerSchema.json"
      }
    },
    "trustees": {
      "type": "array",
      "items": {
        "$ref" : "customer/customerSchema.json"
      }
    },
    "investors": {
      "type": "array",
      "items": {
        "$ref" : "customer/customerSchema.json"
      }
    },
    "companydetails": {
      "$ref": "company/companydetailsSchema.json"
    },
    "shareholderandmembers": {
      "type": "object",
      "$ref": "company/shareholderandmembersSchema.json"
    },
    "accountsettings": {
      "$ref": "accountsettings/accountsettingsSchema.json"
    },
    "companytrustee": {
      "$ref": "company/companydetailsSchema.json"
    },
    "linkedaccounts": {
      "$ref": "linkedaccounts/linkedAccountsApplicationSchema.json"
    },
    "fees": {
      "$ref": "fees/feesSchema.json"
    }
  },
  "additionalProperties": false,
  "allOf":[
    {
      "required": [
        "version",
        "accountType",
        "accountsettings",
        "linkedaccounts"
      ],
      "description": "required for all account types"
    },
    {
      "oneOf":[
        {
          "required": [ "investors" ],
          "description": "required only for individual account"
        },
        {
          "required": [ "companydetails", "directors", "shareholderandmembers" ],
          "description": "required only for company account"
        },
        {
          "required": [ "trustdetails", "trustees", "trustType", "shareholderandmembers" ],
          "description": "required only for Individual Trust account"
        },
        {
          "required": [ "trustdetails", "companytrustee", "trustType", "shareholderandmembers" ],
          "description": "required only for Company Trust account"
        },
        {
          "required": [ "smsfdetails", "trustees", "shareholderandmembers" ],
          "description": "required only for SMSF Individual account"
        },
        {
          "required": [ "smsfdetails", "companytrustee", "directors", "shareholderandmembers" ],
          "description": "required only for SMSF Corporate account"
        }
      ]
    }
  ]
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/service/client_application_company_form_data_v2.json
{
  
    "version": "1.0.0",
    "accountType": "company",
    "companydetails": {
      "companyname": "test",
      "asicregisteredname": "test",
      "acn": "007457141",
      "companyabn": "",
      "agreeconditions": "Verified",
      "industry": {
        "industry": "7412",
        "anzsiccode": "7412",
        "ucmcode": "SIC 0360"
      },
      "companyofficev2": {
        "country": "AU",
        "existingAddressList": [
          {
            "DisplayText": "78 Crimea Street, PARRAMATTA  NSW  2150",
            "country": "AU",
            "valid": true,
            "sameasaddress": "0",
            "AddressIdentifier": "0EOAUEHgvgBwAAAAAIAgEAAAAAm39mEAAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-"
          }
        ],
        "sameasaddress": "0",
        "addressType": "residential",
        "DisplayText": "78 Crimea Street, PARRAMATTA  NSW  2150",
        "AddressIdentifier": "0EOAUEHgvgBwAAAAAIAgEAAAAAm39mEAAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
        "valid": true
      },
      "placeofbusinessv2": {
        "DisplayText": "78 Crimea Street, PARRAMATTA  NSW  2150",
        "country": "AU",
        "valid": true,
        "sameasaddress": "0EOAUEHgvgBwAAAAAIAgEAAAAAm39mEAAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
        "addressType": "residential",
        "AddressIdentifier": "0EOAUEHgvgBwAAAAAIAgEAAAAAm39mEAAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
        "existingAddressList": [
          {
            "DisplayText": "78 Crimea Street, PARRAMATTA  NSW  2150",
            "country": "AU",
            "valid": true,
            "sameasaddress": "0",
            "AddressIdentifier": "0EOAUEHgvgBwAAAAAIAgEAAAAAm39mEAAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-"
          }
        ]
      },
      "taxdetails": {
        "ausTaxDetails": {
          "taxOption": {
            "value": "Tax File Number or exemption not provided",
            "valid": true
          },
          "exemptionReason": {
            "valid": true
          },
          "tfn": {
            "valid": false
          },
          "isTaxCountryAus": {
            "value": true,
            "valid": true
          }
        },
        "isOverseasTaxRes": {
          "value": false,
          "valid": true
        },
        "overseasTaxDetails": [
          
        ]
      },
      "docissuer": "ASIC",
      "issuedate": "28 Feb 2017",
      "documentnumber": "notapplicable",
      "verificationsource": "Website search",
      "englishtranslation": "notapplicable",
      "registeredforgst": "yes",
      "wealthsource": "Business income\/earnings",
      "personalinvestmententity": true
    },
    "directors": [
      {
        "title": "MR",
        "firstname": "test",
        "middlename": "",
        "lastname": "FIRST",
        "preferredname": "",
        "formername": "",
        "dateofbirth": "11\/11\/1988",
        "gender": "male",
        "mobile": {
          "value": "0451223442"
        },
        "email": {
          "value": "test@test.com"
        },
        "preferredcontact": "",
        "isvalid": false,
        "accountType": "company",
        "alternatename": "",
        "sameasresaddress": "true",
        "taxdetails": {
          "ausTaxDetails": {
            "isTaxCountryAus": {
              "value": true,
              "valid": true
            }
          },
          "isOverseasTaxRes": {
            "value": false,
            "valid": true
          },
          "overseasTaxDetails": [
            
          ]
        },
        "identitydocument": {
          
        },
        "resaddressv2": {
          "DisplayText": "78 Crimea Street, PARRAMATTA  NSW  2150",
          "country": "AU",
          "valid": true,
          "sameasaddress": "0EOAUEHgvgBwAAAAAIAgEAAAAAm39mEAAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
          "addressType": "residential",
          "AddressIdentifier": "0EOAUEHgvgBwAAAAAIAgEAAAAAm39mEAAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
          "existingAddressList": [
            {
              "DisplayText": "78 Crimea Street, PARRAMATTA  NSW  2150",
              "country": "AU",
              "valid": true,
              "sameasaddress": "0",
              "AddressIdentifier": "0EOAUEHgvgBwAAAAAIAgEAAAAAm39mEAAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-"
            }
          ]
        },
        "postaladdressv2": {
          "DisplayText": "78 Crimea Street, PARRAMATTA  NSW  2150",
          "country": "AU",
          "valid": true,
          "sameasaddress": "0EOAUEHgvgBwAAAAAIAgEAAAAAm39mEAAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
          "addressType": "postal",
          "AddressIdentifier": "0EOAUEHgvgBwAAAAAIAgEAAAAAm39mEAAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-",
          "existingAddressList": [
            {
              "DisplayText": "78 Crimea Street, PARRAMATTA  NSW  2150",
              "country": "AU",
              "valid": true,
              "sameasaddress": "0",
              "AddressIdentifier": "0EOAUEHgvgBwAAAAAIAgEAAAAAm39mEAAhAA4AAAAAAAAAAAD..2QAAAAA.....wAAAAAAAAAAAAAAAAA3OCBjcmltZWEgc3RyZQA-"
            }
          ]
        }
      }
    ],
    "accountsettings": {
      "professionalspayment": "linkedaccountsonly",
      "investorAccountSettings": [
        {
          "role": "director",
          "isApprover": "true",
          "paymentSetting": "linkedaccountsonly",
          "hasRoles": true,
          "hasApprovers": true
        }
      ],
      "primarycontact": 0,
      "adviserName": "Edward Revis",
      "adviserLocation": "New South Wales",
      "sourceoffunds": "Bonus",
      "powerofattorney": true
    },
    "shareholderandmembers": {
      "needsShareholder": true,
      "needsMember": false,
      "needsBeneficiary": false,
      "needsBeneficialOwner": true,
      "accountType": "company",
      "isMajorShareholder": "yes",
      "investorsWithRoles": [
        {
          "isShareholder": "yes",
          "needsShareholder": true,
          "needsMember": false,
          "needsBeneficiary": false,
          "role": "Director",
          "needsBeneficialOwner": true,
          "isMajorShareholder": "yes"
        }
      ],
      "additionalShareHoldersAndMembers": [
        
      ]
    },
    "linkedaccounts": {
      "primaryLinkedAccount": {
        "accountname": "test",
        "bsb": "063133",
        "accountnumber": "132343213",
        "bsbValidationResultVal": true
      },
      "otherLinkedAccount": [
        
      ]
    },
    "fees": {
      "estamount": "0.00",
      "ongoingFees": {
        "feesComponent": [
          
        ],
        "type": "Ongoing advice fee"
      }
    }
  }

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/builder/v3_JsonSchema/individual_existingForeignRegisteredNull.json
{
  "version": "1.0.0",
  "accountType": "individual",
  "investors": [{
    "gcmUpdated": true,
    "emails": [{
      "email": "deepaky@gmail.com",
      "preferred": false
    }],
    "personRoles": [],
    "phones": [{
      "preferred": false,
      "number": "12345678",
      "phoneType": "Secondary",
      "type": "Phone",
      "areaCode": "04",
      "countryCode": "61"
    },
      {
        "preferred": false,
        "number": "12345689",
        "phoneType": "Secondary",
        "type": "Phone",
        "areaCode": "04",
        "countryCode": "61"
      }],
    "gcmTitleLabel": "Mr",
    "cisId": "12345678903",
    "userName": "12215910",
    "idVerified": true,
    "contactdetails": {
      "label": "0412 345 678",
      "value": "mobile_0412345678"
    },
    "taxdetails": {
      "ausTaxDetails": {
        "tfn": {
          "valid": false
        },
        "taxOption": {
          "valid": true,
          "value": "Exemption Reason provided"
        },
        "isTaxCountryAus": {
          "valid": true,
          "value": false
        },
        "exemptionReason": {
          "valid": true,
          "value": "non_au_resi"
        }
      },
      "overseasTaxDetails": [],
      "selectedOverseasTaxCountry": {
        "valid": true,
        "value": "DE"
      }
    },
    "isDuplicate": false,
    "registered": false,
    "tfnProvided": false,
    "investorType": "individual",
    "displayTaxOptions": true,
    "title": "MR",
    "firstname": "Asas",
    "lastname": "Asasa",
    "dateofbirth": "20/04/1983",
    "gender": "Male",
    "mobile": {
      "value": "0412345678"
    },
    "email": {
      "value": "deepaky@gmail.com"
    },
    "preferredcontact": "mobile",
    "isvalid": true,
    "accountType": "individual",
    "resaddress": {
      "city": "Parramatta",
      "domicile": true,
      "countryCode": "AU",
      "internationalAddress": false,
      "mailingAddress": true,
      "standardAddressFormat": false,
      "componentised": false,
      "addressLine1": "Unit 10",
      "addressLine2": "4  Charles  Street",
      "state": "NSW",
      "postcode": "2150",
      "country": "Australia",
      "existingAddressList": []
    },
    "postaladdress": {
      "city": "Parramatta",
      "domicile": true,
      "countryCode": "AU",
      "internationalAddress": false,
      "mailingAddress": true,
      "standardAddressFormat": false,
      "addressLine1": "Unit 10",
      "addressLine2": "4  Charles  Street",
      "state": "NSW",
      "postcode": "2150",
      "country": "Australia",
      "existingAddressList": []
    },
    "taxcountry": "AU",
    "taxoption": "",
    "tfn": "",
    "exemptionreason": ""
  }],
  "accountsettings": {
    "professionalspayment": "linkedaccountsonly",
    "investorAccountSettings": [{
      "paymentSetting": "nopayments",
      "hasRoles": false,
      "hasApprovers": false
    }],
    "primarycontact": 0,
    "adviserName": "Richard Peterson",
    "adviserLocation": "New South Wales",
    "sourceoffunds": "Business income/earnings",
    "powerofattorney": false
  },
  "linkedaccounts": {
    "primaryLinkedAccount": {
      "accountname": "dadasd",
      "bsb": "062062",
      "accountnumber": "123456",
      "bsbValidationResultVal": true
    },
    "otherLinkedAccount": []
  },
  "fees": {
    "estamount": "0.00",
    "ongoingFees": {
      "feesComponent": [],
      "type": "Ongoing advice fee"
    },
    "licenseeFees": {
      "feesComponent": [{
        "label": "Percentage fee component",
        "listedSecurities": "2.00",
        "managedFund": "1.00",
        "managedPortfolio": "0.00",
        "cash": "0.00",
        "termDeposit": "0.00",
        "slidingScaleFeeTier": [],
        "valid": true
      }],
      "type": "Licensee advice fee"
    }
  }
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/model/joint-new-and-panorama-and-gcm-4.json
{
  "accountType": "joint",
  "approvalType": "online",
  "version": "1.0.0",
  "investors": [
    {
      "displayTaxOptions": true,
      "taxcountry": "AU",
      "taxoption": "Exemption Reason provided",
      "exemptionreason": "tax_exempt",
      "userName": "74943018",
      "idVerified": true,
      "registered": false,
      "tfnProvided": false,
      "investorType": "individual",
      "cisId": "71034910078",
      "title": "MR",
      "gcmTitleLabel": "Mr",
      "gender": "Male",
      "active": false,
      "accountType": "joint",
      "firstname": "Sdfsf",
      "lastname": "Sdfsf",
      "dateofbirth": "18/06/1988",
      "resaddress": {
        "state": "NSW",
        "city": "Sydney",
        "postcode": "2000",
        "countryCode": "AU",
        "country": "Australia",
        "domicile": true,
        "mailingAddress": true,
        "internationalAddress": false,
        "addressLine1": "275 Market Street",
        "standardAddressFormat": false
      },
      "postaladdress": {
        "state": "NSW",
        "city": "Sydney",
        "postcode": "2000",
        "countryCode": "AU",
        "country": "Australia",
        "domicile": true,
        "mailingAddress": true,
        "internationalAddress": false,
        "addressLine1": "275 Market Street",
        "standardAddressFormat": false
      },
      "isDuplicate": true,
      "mobile": {
        "value": "0412345678"
      },
      "email": {
        "value": "sdfsff@efsfd.com"
      },
      "contactdetails": {
        "value": "homenumber_04123456789",
        "label": "04 123 456 789"
      },
      "preferredcontact": "homenumber",
      "homenumber": {
        "areaCode": "04",
        "concatenatedNumber": "04123456789",
        "value": "123456789"
      },
      "isvalid": true
    },
    {
      "isvalid": true,
      "key": {
        "clientId": "1511C500CF7073650C5A9F7A657431294EC50DD43A7489D4"
      },
      "userName": "bae6-bd4f-c6",
      "emails": [
        {
          "email": "mail@mail.com",
          "preferred": false,
          "emailType": "Primary"
        }
      ],
      "phones": [
        {
          "preferred": true,
          "number": "0412344567",
          "phoneType": "Primary",
          "type": "Phone",
          "label": "Mobile - primary"
        }
      ],
      "idVerified": true,
      "registered": true,
      "tfnProvided": false,
      "exemptionreason": "norfolk_island_res",
      "personRoles": [
        "Owner"
      ],
      "gcmId": "237328674",
      "investorType": "INDIVIDUAL",
      "tfnExemptId": "99",
      "cisId": "44729910038",
      "title": "Mr",
      "gender": "Male",
      "accountType": "joint",
      "firstname": "Testone",
      "middlename": "Mid",
      "lastname": "Last",
      "preferredname": "Perff",
      "dateofbirth": "04 May 1990",
      "mobile": {
        "value": "0412344567"
      },
      "email": {
        "value": "mail@mail.com"
      },
      "isDuplicate": true
    },
    {
      "displayTaxOptions": true,
      "cismandatory": true,
      "title": "MR",
      "firstname": "eeee",
      "middlename": "eeee",
      "lastname": "eee",
      "preferredname": "eee",
      "formername": "",
      "dateofbirth": "03/03/1978",
      "gender": "male",
      "mobile": {
        "value": "0433232323"
      },
      "email": {
        "value": "sssss@mail.com"
      },
      "preferredcontact": "mobile",
      "isvalid": true,
      "accountType": "joint",
      "alternatename": "eeee",
      "wealthsource": "Business profits",
      "identitydocument": {
        "photodocuments": {
          "agecard": {
            "documentIssuer": "ACT",
            "verificationSource": "original",
            "englishTranslation": "Not Applicable",
            "documentNumber": "w333333",
            "expiryDate": "04/04/2030",
            "accreditedenglishtrans": "notapplicable"
          },
          "valid": true
        }
      },
      "resaddress": {
        "componentised": true,
        "unitNumber": "",
        "streetNumber": "",
        "streetName": "Dddd",
        "suburb": "SYDNEY",
        "state": "NSW",
        "postcode": "2000",
        "country": "AU",
        "verified": true,
        "addressType": "residential",
        "existingAddressList": [
          {
            "componentised": true,
            "unitNumber": "",
            "streetNumber": "",
            "streetName": "Dddd",
            "suburb": "SYDNEY",
            "state": "NSW",
            "postcode": "2000",
            "country": "AU",
            "verified": true,
            "confirmed": true,
            "valid": true,
            "sameasaddress": "0",
            "addressType": "residential",
            "id": "775834"
          }
        ],
        "sameasaddress": "0",
        "confirmed": true,
        "valid": true
      },
      "postaladdress": {
        "componentised": true,
        "unitNumber": "",
        "streetNumber": "",
        "streetName": "Dddd",
        "suburb": "SYDNEY",
        "state": "NSW",
        "postcode": "2000",
        "country": "AU",
        "verified": true,
        "confirmed": true,
        "valid": true,
        "sameasaddress": "430640",
        "addressType": "residential",
        "id": "430640",
        "existingAddressList": [
          {
            "componentised": true,
            "unitNumber": "",
            "streetNumber": "",
            "streetName": "Dddd",
            "suburb": "SYDNEY",
            "state": "NSW",
            "postcode": "2000",
            "country": "AU",
            "verified": true,
            "confirmed": true,
            "valid": true,
            "sameasaddress": "0",
            "addressType": "residential",
            "id": "430640"
          }
        ]
      },
      "taxcountry": "AU",
      "taxoption": "Tax File Number or exemption not provided"
    }
  ],
  "accountsettings": {
    "professionalspayment": "linkedaccountsonly",
    "investorAccountSettings": [
      {
        "paymentSetting": "linkedaccountsonly",
        "hasRoles": false,
        "hasApprovers": false
      },
      {
        "paymentSetting": "nopayments",
        "hasRoles": false,
        "hasApprovers": false
      },
      {
        "paymentSetting": "allpayments",
        "hasRoles": false,
        "hasApprovers": false
      }
    ],
    "primarycontact": 0,
    "adviserName": "Michelle Hicks",
    "adviserLocation": "South Australia",
    "sourceoffunds": "Business profits"
  },
  "linkedaccounts": {
    "primaryLinkedAccount": {
      "accountname": "ddddd",
      "bsb": "082124",
      "accountnumber": "3647343",
      "bsbValidationResultVal": true
    },
    "otherLinkedAccount": []
  },
  "fees": {
    "estamount": "3.00",
    "ongoingFees": {
      "feesComponent": [
        {
          "listedSecurities": "1.00",
          "managedFund": "0.00",
          "managedPortfolio": "0.00",
          "termDeposit": "0.00",
          "cash": "0.00",
          "label": "Percentage fee component",
          "valid": true
        }
      ],
      "type": "Ongoing advice fee"
    },
    "licenseeFees": {
      "feesComponent": [
        {
          "termDeposit": "true",
          "slidingScaleFeeTier": [
            {
              "lowerBound": "0.00",
              "upperBound": "11111.00",
              "percentage": "1.00"
            },
            {
              "lowerBound": "11111.00",
              "upperBound": "",
              "percentage": "1.00"
            }
          ],
          "label": "Sliding scale fee component"
        }
      ],
      "type": "Licensee advice fee"
    }
  }
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/service/client_application_superpension_form.json
{
  "version": "1.0.0",
  "accountType": "superPension",
  "pensioneligibility": {
    "conditionRelease": "oth",
    "eligibilityCriteria": "unpsv"
  },
  "investors": [
    {
      "emails": [

      ],
      "personRoles": [

      ],
      "phones": [

      ],
      "displayTaxOptions": true,
      "cismandatory": true,
      "wealthsource": "Business profits",
      "title": "MR",
      "firstname": "Robert",
      "middlename": "",
      "lastname": "Diego",
      "preferredname": "",
      "formername": "",
      "dateofbirth": "02\/02\/1935",
      "gender": "male",
      "mobile": {
        "value": "0425836901"
      },
      "email": {
        "value": "diego@test.com"
      },
      "preferredcontact": "mobile",
      "isvalid": true,
      "alternatename": "",
      "accountType": "superPension",
      "identitydocument": {
        "photodocuments": {
          "driverlicence": {
            "documentIssuer": "NSW",
            "expiryDate": "01\/10\/2017",
            "documentNumber": "25896314",
            "verificationSource": "original",
            "englishTranslation": "Not Applicable",
            "accreditedenglishtrans": "notapplicable"
          },
          "valid": true
        }
      },
      "resaddress": {
        "componentised": true,
        "addressType": "residential",
        "unitNumber": "",
        "streetNumber": "135-151",
        "streetName": "Clarence",
        "streetType": "STREET",
        "suburb": "SYDNEY",
        "state": "NSW",
        "postcode": "2000",
        "country": "AU",
        "id": "552983",
        "sameasaddress": "552983",
        "confirmed": true,
        "valid": true,
        "verified": true,
        "existingAddressList": [
          {
            "componentised": true,
            "addressType": "residential",
            "unitNumber": "",
            "streetNumber": "135-151",
            "streetName": "Clarence",
            "streetType": "STREET",
            "suburb": "SYDNEY",
            "state": "NSW",
            "postcode": "2000",
            "country": "AU",
            "id": "552983",
            "sameasaddress": "0",
            "confirmed": true,
            "valid": true,
            "verified": true,
            "existingAddressList": [

            ]
          }
        ]
      },
      "postaladdress": {
        "componentised": true,
        "addressType": "residential",
        "unitNumber": "",
        "streetNumber": "135-151",
        "streetName": "Clarence",
        "streetType": "STREET",
        "suburb": "SYDNEY",
        "state": "NSW",
        "postcode": "2000",
        "country": "AU",
        "id": "408118",
        "sameasaddress": "408118",
        "confirmed": true,
        "valid": true,
        "verified": true,
        "existingAddressList": [
          {
            "componentised": true,
            "addressType": "residential",
            "unitNumber": "",
            "streetNumber": "135-151",
            "streetName": "Clarence",
            "streetType": "STREET",
            "suburb": "SYDNEY",
            "state": "NSW",
            "postcode": "2000",
            "country": "AU",
            "id": "408118",
            "sameasaddress": "0",
            "confirmed": true,
            "valid": true,
            "verified": true,
            "existingAddressList": [

            ]
          }
        ]
      },
      "taxcountry": "AU",
      "taxoption": "pensioner"
    }
  ],
  "accountsettings": {
    "professionalspayment": "linkedaccountsonly",
    "investorAccountSettings": [
      {
        "paymentSetting": "nopayments",
        "hasRoles": false,
        "hasApprovers": false
      }
    ],
    "primarycontact": 0,
    "adviserName": "Marco Kwok",
    "adviserLocation": "Western Australia",
    "sourceoffunds": "Business profits"
  },
  "linkedaccounts": {
    "primaryLinkedAccount": {
      "accountname": "TestAccount",
      "bsb": "062001",
      "accountnumber": "25896314",
      "nickname": "",
      "bsbValidationResultVal": true
    },
    "otherLinkedAccount": [

    ]
  },
  "fees": {
    "estamount": "0.00",
    "ongoingFees": {
      "feesComponent": [

      ],
      "type": "Ongoing advice fee"
    },
    "licenseeFees": {
      "feesComponent": [

      ],
      "type": "Licensee advice fee"
    }
  }
}
