=== Aim4dStars/work/nextgenx/src/main/resources/com/bt/nextgen/api/draftaccount/schemas/v1/accountApplicationSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "javaType" : "com.bt.nextgen.api.draftaccount.schemas.v1.OnboardingApplicationFormData",
  "type": "object",
  "properties": {
    "version": {
      "type": "string",
      "description": "this is the application Account JSON Schema Version number supported by client & server (http://semver.org/)",
      "pattern": "^[1-99]{1}.[0-99]{1}.[0-99]{1}$"
    },
    "parentProductName" : {
      "type": "string",
      "description": "This field contains the parent product name for this account."
    },
    "accountType": {
      "$ref": "base/accountTypeEnum.json"
    },
    "approvalType": {
      "$ref": "base/approvalTypeEnum.json",
      "description": "This field indicates the type of approval method selected for this account."
    },
    "trustType": {
      "$ref": "base/trustTypeEnum.json"
    },
    "trustdetails": {
      "type": "object",
      "$ref": "trust/trustdetailsSchema.json"
    },
    "pensioneligibility": {
      "type": "object",
      "$ref": "pensioneligibility/pensionEligibilitySchema.json",
      "description": "This schema is used for the Super Pension eligibility applicable only for super pension account."
     },
    "smsfdetails": {
      "type": "object",
      "$ref": "smsf/smsfdetailsSchema.json"
    },
    "directors": {
      "type": "array",
      "items": {
        "$ref" : "customer/customerSchema.json"
      }
    },
    "trustees": {
      "type": "array",
      "items": {
        "$ref" : "customer/customerSchema.json"
      }
    },
    "investors": {
      "type": "array",
      "items": {
        "$ref" : "customer/customerSchema.json"
      }
    },
    "companydetails": {
      "$ref": "company/companydetailsSchema.json"
    },
    "shareholderandmembers": {
      "type": "object",
      "$ref": "company/shareholderandmembersSchema.json"
    },
    "accountsettings": {
      "$ref": "accountsettings/accountsettingsSchema.json"
    },
    "companytrustee": {
      "$ref": "company/companydetailsSchema.json"
    },
    "linkedaccounts": {
      "$ref": "linkedaccounts/linkedAccountsApplicationSchema.json"
    },
    "fees": {
      "$ref": "fees/feesSchema.json"
    }
  },
  "additionalProperties": false,
  "allOf":[
    {
      "required": [
        "version",
        "accountType",
        "accountsettings",
        "linkedaccounts"
      ],
      "description": "required for all account types"
    },
    {
      "oneOf":[
        {
          "required": [ "investors" ],
          "description": "required only for individual account"
        },
        {
          "required": [ "companydetails", "directors", "shareholderandmembers" ],
          "description": "required only for company account"
        },
        {
          "required": [ "trustdetails", "trustees", "trustType", "shareholderandmembers" ],
          "description": "required only for Individual Trust account"
        },
        {
          "required": [ "trustdetails", "companytrustee", "trustType", "shareholderandmembers" ],
          "description": "required only for Company Trust account"
        },
        {
          "required": [ "smsfdetails", "trustees", "shareholderandmembers" ],
          "description": "required only for SMSF Individual account"
        },
        {
          "required": [ "smsfdetails", "companytrustee", "directors", "shareholderandmembers" ],
          "description": "required only for SMSF Corporate account"
        }
      ]
    }
  ]
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/builder/v3_JsonSchema/superAccumulation.json
{
  "version": "1.0.0",
  "accountType": "superAccumulation",
  "approvalType": "online",
  "investors": [
    {
      "emails": [
      ],
      "personRoles": [
      ],
      "phones": [
      ],
      "displayTaxOptions": true,
      "cismandatory": true,
      "wealthsource": "Business income\/earnings",
      "title": "MR",
      "firstname": "Melroy",
      "middlename": "",
      "lastname": "Smith",
      "preferredname": "",
      "formername": "",
      "dateofbirth": "10\/10\/1980",
      "gender": "male",
      "mobile": {
        "value": "0456565656"
      },
      "email": {
        "value": "mel@smith.com"
      },
      "preferredcontact": "mobile",
      "isvalid": true,
      "alternatename": "",
      "accountType": "superAccumulation",
      "identitydocument": {
        "photodocuments": {
          "driverlicence": {
            "documentIssuer": "ACT",
            "expiryDate": "10\/10\/2019",
            "documentNumber": "432431",
            "verificationSource": "original",
            "englishTranslation": "Not Applicable",
            "accreditedenglishtrans": "notapplicable"
          },
          "valid": true
        }
      },
      "resaddress": {
        "componentised": true,
        "addressType": "residential",
        "unitNumber": "",
        "streetNumber": "51-57",
        "streetName": "Pitt",
        "streetType": "STREET",
        "suburb": "SYDNEY",
        "state": "NSW",
        "postcode": "2000",
        "country": "AU",
        "sameasaddress": "0",
        "confirmed": true,
        "valid": true,
        "verified": true,
        "existingAddressList": [
          {
            "componentised": true,
            "addressType": "residential",
            "unitNumber": "",
            "streetNumber": "51-57",
            "streetName": "Pitt",
            "streetType": "STREET",
            "suburb": "SYDNEY",
            "state": "NSW",
            "postcode": "2000",
            "country": "AU",
            "id": "757268",
            "sameasaddress": "0",
            "confirmed": true,
            "valid": true,
            "verified": true,
            "existingAddressList": [
            ]
          }
        ]
      },
      "postaladdress": {
        "componentised": true,
        "addressType": "residential",
        "unitNumber": "",
        "streetNumber": "51-57",
        "streetName": "Pitt",
        "streetType": "STREET",
        "suburb": "SYDNEY",
        "state": "NSW",
        "postcode": "2000",
        "country": "AU",
        "id": "450506",
        "sameasaddress": "450506",
        "confirmed": true,
        "valid": true,
        "verified": true,
        "existingAddressList": [
          {
            "componentised": true,
            "addressType": "residential",
            "unitNumber": "",
            "streetNumber": "51-57",
            "streetName": "Pitt",
            "streetType": "STREET",
            "suburb": "SYDNEY",
            "state": "NSW",
            "postcode": "2000",
            "country": "AU",
            "id": "450506",
            "sameasaddress": "0",
            "confirmed": true,
            "valid": true,
            "verified": true,
            "existingAddressList": [
            ]
          }
        ]
      },
      "taxcountry": "AU",
      "taxoption": "Tax File Number provided",
      "tfn": "11111111"
    }
  ],
  "accountsettings": {
    "professionalspayment": "linkedaccountsonly",
    "investorAccountSettings": [
      {
        "paymentSetting": "nopayments",
        "hasRoles": false,
        "hasApprovers": false
      }
    ],
    "primarycontact": 0,
    "adviserName": "Richard Peterson",
    "adviserLocation": "New South Wales",
    "sourceoffunds": "Bonus"
  },
  "linkedaccounts": {
    "primaryLinkedAccount": {
      "accountname": "test account",
      "bsb": "062000",
      "accountnumber": "6546542",
      "nickname": "",
      "bsbValidationResultVal": true
    },
    "otherLinkedAccount": [
    ]
  },
  "fees": {
    "estamount": "0.00",
    "ongoingFees": {
      "feesComponent": [
      ],
      "type": "Ongoing advice fee"
    },
    "licenseeFees": {
      "feesComponent": [
      ],
      "type": "Licensee advice fee"
    }
  }
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/model/trust-individual-regulated-2.json
{
  "trustType": "regulated",
  "version": "1.0.0",
  "accountType": "individualTrust",
  "trustdetails": {
    "trustname": "sddsds",
    "businessname": "sdsdsd",
    "abn": "",
    "regdate": "03/03/2001",
    "registrationstate": "NSW",
    "registeredforgst": "yes",
    "trusttype": "regulated",
    "licensingnumber": "232232",
    "trustconfirmedregulated": "Verified",
    "wealthsource": "Additional Sources",
    "additionalsourceofwealth": "dsdsd",
    "industry": {
      "industry": "7412",
      "anzsiccode": "7412",
      "ucmcode": "SIC 0360"
    },
    "address": {
      "componentised": true,
      "unitNumber": "",
      "streetNumber": "28",
      "streetName": "West",
      "streetType": "STREET",
      "suburb": "NORTH SYDNEY",
      "state": "NSW",
      "postcode": "2060",
      "country": "AU",
      "verified": true,
      "addressType": "residential",
      "existingAddressList": [
        {
          "componentised": true,
          "unitNumber": "",
          "streetNumber": "28",
          "streetName": "West",
          "streetType": "STREET",
          "suburb": "NORTH SYDNEY",
          "state": "NSW",
          "postcode": "2060",
          "country": "AU",
          "verified": true,
          "confirmed": true,
          "valid": true,
          "sameasaddress": "0",
          "addressType": "residential",
          "id": "957700"
        }
      ],
      "sameasaddress": "0",
      "confirmed": true,
      "valid": true
    },
    "taxoption": "Exemption Reason provided",
    "exemptionreason": "norfolk_island_res"
  },
  "trustees": [
    {
      "title": "MR",
      "firstname": "sdsd",
      "middlename": "dsds",
      "lastname": "dsds",
      "preferredname": "dsd",
      "formername": "",
      "dateofbirth": "03/03/1978",
      "gender": "male",
      "mobile": {
        "value": "0422323232"
      },
      "email": {
        "value": "asasa@email.com"
      },
      "preferredcontact": "email",
      "isvalid": true,
      "accountType": "individualTrust",
      "alternatename": "dsd",
      "identitydocument": {
        "photodocuments": {
          "agecard": {
            "documentIssuer": "NT",
            "verificationSource": "certifiedcopy",
            "englishTranslation": "Not Applicable",
            "documentNumber": "34343",
            "expiryDate": "04/04/2020",
            "accreditedenglishtrans": "notapplicable"
          },
          "valid": true
        }
      },
      "resaddress": {
        "componentised": true,
        "unitNumber": "",
        "streetNumber": "28",
        "streetName": "West",
        "streetType": "STREET",
        "suburb": "NORTH SYDNEY",
        "state": "NSW",
        "postcode": "2060",
        "country": "AU",
        "verified": true,
        "confirmed": true,
        "valid": true,
        "sameasaddress": "233013",
        "addressType": "residential",
        "id": "233013",
        "existingAddressList": [
          {
            "componentised": true,
            "unitNumber": "",
            "streetNumber": "28",
            "streetName": "West",
            "streetType": "STREET",
            "suburb": "NORTH SYDNEY",
            "state": "NSW",
            "postcode": "2060",
            "country": "AU",
            "verified": true,
            "confirmed": true,
            "valid": true,
            "sameasaddress": "0",
            "addressType": "residential",
            "id": "233013"
          },
          {
            "componentised": false,
            "addressLine1": "Sdsdsd",
            "addressLine2": "",
            "country": "DZ",
            "city": "sdssds",
            "pin": "2222",
            "verified": true,
            "confirmed": true,
            "valid": true,
            "sameasaddress": "0",
            "addressType": "postal",
            "id": "424685"
          }
        ]
      },
      "postaladdress": {
        "componentised": false,
        "addressLine1": "Sdsdsd",
        "addressLine2": "",
        "country": "DZ",
        "city": "sdssds",
        "pin": "2222",
        "verified": true,
        "addressType": "postal",
        "existingAddressList": [
          {
            "componentised": true,
            "unitNumber": "",
            "streetNumber": "28",
            "streetName": "West",
            "streetType": "STREET",
            "suburb": "NORTH SYDNEY",
            "state": "NSW",
            "postcode": "2060",
            "country": "AU",
            "verified": true,
            "confirmed": true,
            "valid": true,
            "sameasaddress": "0",
            "addressType": "residential",
            "id": "584739"
          },
          {
            "componentised": false,
            "addressLine1": "Sdsdsd",
            "addressLine2": "",
            "country": "DZ",
            "city": "sdssds",
            "pin": "2222",
            "verified": true,
            "confirmed": true,
            "valid": true,
            "sameasaddress": "0",
            "addressType": "postal",
            "id": "510302"
          }
        ],
        "sameasaddress": "0",
        "confirmed": true,
        "valid": true
      }
    },
    {
      "isvalid": true,
      "key": {
        "clientId": "6F193B9375C3B657893857C7C4DA6143CBFBE74EFEFF6E33"
      },
      "userName": "",
      "emails": [
        {
          "email": "Dummy@BTFinancialGroup.com",
          "preferred": false,
          "emailType": "Primary"
        }
      ],
      "phones": [
        {
          "preferred": true,
          "number": "0419123456",
          "phoneType": "Primary",
          "type": "Phone",
          "label": "Mobile - primary"
        }
      ],
      "idVerified": true,
      "registered": true,
      "tfnProvided": false,
      "exemptionreason": "norfolk_island_res",
      "personRoles": [
        "Owner"
      ],
      "gcmId": "201602112",
      "investorType": "INDIVIDUAL",
      "tfnExemptId": "99",
      "gender": "Male",
      "accountType": "individualTrust",
      "firstname": "Personbcaciag",
      "middlename": "Personbcaciag",
      "lastname": "Personbcaciag",
      "dateofbirth": "01 Jan 1980",
      "mobile": {
        "value": "0419123456"
      },
      "email": {
        "value": "Dummy@BTFinancialGroup.com"
      },
      "isDuplicate": false
    }
  ],
  "accountsettings": {
    "professionalspayment": "allpayments",
    "investorAccountSettings": [
      {
        "isApprover": "true",
        "paymentSetting": "linkedaccountsonly",
        "hasRoles": false,
        "hasApprovers": true
      },
      {
        "isApprover": "true",
        "paymentSetting": "nopayments",
        "hasRoles": false,
        "hasApprovers": true
      }
    ],
    "primarycontact": 0,
    "adviserName": "Paul Folks",
    "adviserLocation": "South Australia",
    "sourceoffunds": "Business profits"
  },
  "shareholderandmembers": {
    "needsShareholder": false,
    "needsMember": false,
    "needsBeneficiary": true,
    "accountType": "individualTrust",
    "hasbeneficiaryclasses": "yes",
    "beneficiaryclassdetails": "wwewew",
    "investorsWithRoles": [
      {
        "isBeneficiary": "yes",
        "needsShareholder": false,
        "needsMember": false,
        "needsBeneficiary": true
      },
      {
        "isBeneficiary": "no",
        "needsShareholder": false,
        "needsMember": false,
        "needsBeneficiary": true
      }
    ],
    "additionalShareHoldersAndMembers": []
  },
  "linkedaccounts": {
    "primaryLinkedAccount": {
      "accountname": "wewew",
      "bsb": "082124",
      "accountnumber": "2323232",
      "nickname": "ewew",
      "directdebitamount": "23.00",
      "bsbValidationResultVal": true
    },
    "otherLinkedAccount": []
  },
  "fees": {
    "estamount": "0.00",
    "ongoingFees": {
      "feesComponent": [
        {
          "listedSecurities": "true",
          "managedFund": "true",
          "managedPortfolio": "true",
          "slidingScaleFeeTier": [
            {
              "lowerBound": "0.00",
              "upperBound": "3333333.00",
              "percentage": "1.00"
            },
            {
              "lowerBound": "3333333.00",
              "upperBound": "",
              "percentage": "0.00"
            }
          ],
          "label": "Sliding scale fee component"
        }
      ],
      "type": "Ongoing advice fee"
    },
    "licenseeFees": {
      "feesComponent": [
        {
          "listedSecurities": "0.00",
          "managedFund": "0.00",
          "managedPortfolio": "1.00",
          "termDeposit": "0.00",
          "cash": "1.00",
          "label": "Percentage fee component",
          "valid": true
        }
      ],
      "type": "Licensee advice fee"
    }
  }
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/model/trust-corporate-invscheme-empty-1.json
{
  "trustType": "invscheme",
  "version": "1.0.0",
  "accountType": "corporateTrust",
  "trustdetails": {
    "trustname": "",
    "abn": "",
    "trusttype": "invscheme",
    "industry": {
    },
    "address": {
      "componentised": false,
      "country": "AU",
      "addressType": "residential",
      "sameasaddress": "0",
      "valid": false
    }
  },
  "companytrustee": {
    "companyabn": "",
    "industry": {
    },
    "companyoffice": {
      "componentised": false,
      "country": "AU",
      "addressType": "residential",
      "sameasaddress": "0",
      "valid": false
    },
    "placeofbusiness": {
      "componentised": false,
      "country": "AU",
      "addressType": "residential",
      "sameasaddress": "0",
      "valid": false
    }
  },
  "directors": [{
    "title": "",
    "firstname": "",
    "middlename": "",
    "lastname": "",
    "preferredname": "",
    "formername": "",
    "gender": "",
    "mobile": {
      "value": ""
    },
    "email": {
      "value": ""
    },
    "preferredcontact": "",
    "isvalid": false,
    "accountType": "corporateTrust",
    "alternatename": ""
  }],
  "accountsettings": {
    "investorAccountSettings": [{
      "isApprover": "true",
      "hasRoles": false,
      "hasApprovers": true
    }],
    "primarycontact": 0,
    "adviserName": "Paul Folks",
    "adviserLocation": "South Australia"
  },
  "shareholderandmembers": {
    "needsShareholder": true,
    "needsMember": false,
    "needsBeneficiary": true,
    "needsBeneficialOwner": true,
    "accountType": "corporateTrust",
    "investorsWithRoles": [{
      "needsShareholder": true,
      "needsMember": false,
      "needsBeneficiary": true,
      "needsBeneficialOwner": true
    }],
    "additionalShareHoldersAndMembers": []
  },
  "linkedaccounts": {
    "primaryLinkedAccount": {
    },
    "otherLinkedAccount": []
  },
  "fees": {
    "estamount": "0.00",
    "ongoingFees": {
      "feesComponent": [],
      "type": "Ongoing advice fee"
    },
    "licenseeFees": {
      "feesComponent": [],
      "type": "Licensee advice fee"
    }
  }
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/service/client_application_crsData_invalidExemptReason.json
{
    "version": "1.0.0",
    "accountType": "individual",
    "investors": [
      {
        "displayTaxOptions": true,
        "cismandatory": true,
        "title": "MR",
        "firstname": "test",
        "middlename": "",
        "lastname": "one",
        "preferredname": "",
        "formername": "",
        "dateofbirth": "11\/11\/1990",
        "gender": "male",
        "mobile": {
          "value": ""
        },
        "email": {
          "value": ""
        },
        "preferredcontact": "",
        "isvalid": false,
        "accountType": "individual",
        "alternatename": "",
        "wealthsource": "Business income\/earnings",
        "sameasresaddress": "true",
        "taxdetails": {
          "ausTaxDetails": {
            "taxOption": {
              "value": "Exemption Reason provided",
              "valid": true
            },
            "exemptionReason": {
			  "value": "abc",
              "valid": true
            },
            "tfn": {
              "valid": false
            },
            "isTaxCountryAus": {
              "value": true,
              "valid": true
            }
          },
          "isOverseasTaxRes": {
            "value": true,
            "valid": true
          },
          "overseasTaxDetails": [
            {
              "overseasTaxCountry": {
                "value": "AL",
                "valid": true
              },
              "tinOption": {
                "value": "Exemption Reason provided",
                "valid": true
              },
              "tinExemptionReason": {
                "value": "UNDER_AGED",
                "valid": true
              },
              "tin": {
                "valid": true
              }
            }
          ]
        },
        "identitydocument": {
          
        },
        "resaddressv2": {
          "country": "AU",
          "sameasaddress": "0",
          "addressType": "residential",
          "DisplayText": "",
          "valid": false
        },
        "postaladdressv2": {
          "country": "AU",
          "sameasaddress": "0",
          "addressType": "postal",
          "DisplayText": "",
          "valid": false
        },
        "taxcountry": "AU",
        "taxoption": ""
      }
    ],
    "accountsettings": {
      "investorAccountSettings": [
        {
          "hasRoles": false,
          "hasApprovers": false
        }
      ],
      "primarycontact": 0,
      "adviserName": "Edward Revis",
      "adviserLocation": "New South Wales"
    },
    "linkedaccounts": {
      "primaryLinkedAccount": {
        
      },
      "otherLinkedAccount": [
        
      ]
    },
    "fees": {
      "estamount": "0.00",
      "ongoingFees": {
        "feesComponent": [
          
        ],
        "type": "Ongoing advice fee"
      }
    }
	}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/model/joint-new-1.json
{
  "accountType": "joint",
  "version": "1.0.0",
  "investors": [{
    "displayTaxOptions": true,
    "cismandatory": true,
    "title": "MR",
    "firstname": "aaa",
    "middlename": "aaaa",
    "lastname": "aaaa",
    "preferredname": "asas",
    "formername": "",
    "dateofbirth": "03/03/1989",
    "gender": "male",
    "mobile": {
      "value": "0422323234"
    },
    "email": {
      "value": "mail@email.com"
    },
    "preferredcontact": "mobile",
    "isvalid": true,

    "accountType": "joint",
    "alternatename": "asasa",
    "wealthsource": "Additional Sources",
    "additionalsourceofwealth": "dsdsds",
    "identitydocument": {
      "photodocuments": {
        "passport": {
          "documentIssuer": "Australia",
          "issueDate": "01/01/2010",
          "expiryDate": "02/02/2020",
          "documentNumber": "weewew",
          "verificationSource": "certifiedcopy",
          "englishTranslation": "Not Applicable",
          "accreditedenglishtrans": "notapplicable"
        },
        "valid": true
      }
    },
    "resaddress": {
      "componentised": true,
      "unitNumber": "",
      "streetNumber": "",
      "streetName": "Dsdsds",
      "suburb": "SYDNEY",
      "state": "NSW",
      "postcode": "2000",
      "country": "AU",
      "verified": true,
      "addressType": "residential",
      "existingAddressList": [{
        "componentised": true,
        "unitNumber": "",
        "streetNumber": "",
        "streetName": "Dsdsds",
        "suburb": "SYDNEY",
        "state": "NSW",
        "postcode": "2000",
        "country": "AU",
        "verified": true,
        "confirmed": true,
        "valid": true,
        "sameasaddress": "0",
        "addressType": "residential",
        "id": "163808"
      }],
      "sameasaddress": "0",
      "confirmed": true,
      "valid": true
    },
    "postaladdress": {
      "componentised": true,
      "unitNumber": "",
      "streetNumber": "",
      "streetName": "Dsdsds",
      "suburb": "SYDNEY",
      "state": "NSW",
      "postcode": "2000",
      "country": "AU",
      "verified": true,
      "confirmed": true,
      "valid": true,
      "sameasaddress": "178340",
      "addressType": "residential",
      "id": "178340",
      "existingAddressList": [{
        "componentised": true,
        "unitNumber": "",
        "streetNumber": "",
        "streetName": "Dsdsds",
        "suburb": "SYDNEY",
        "state": "NSW",
        "postcode": "2000",
        "country": "AU",
        "verified": true,
        "confirmed": true,
        "valid": true,
        "sameasaddress": "0",
        "addressType": "residential",
        "id": "178340"
      }]
    },
    "taxcountry": "AU",
    "taxoption": "Exemption Reason provided",
    "exemptionreason": "fin_busi_provid"
  }],
  "accountsettings": {
    "professionalspayment": "linkedaccountsonly",
    "investorAccountSettings": [{
      "paymentSetting": "nopayments",
      "hasRoles": false,
      "hasApprovers": false
    }],
    "primarycontact": 0,
    "adviserName": "Michelle Hicks",
    "adviserLocation": "South Australia",
    "sourceoffunds": "Bonus"
  },
  "linkedaccounts": {
    "primaryLinkedAccount": {
      "accountname": "sddss",
      "bsb": "082124",
      "accountnumber": "2323232",
      "nickname": "23232",
      "directdebitamount": "23.00",
      "bsbValidationResultVal": true
    },
    "otherLinkedAccount": []
  },
  "fees": {
    "estamount": "0.00",
    "ongoingFees": {
      "feesComponent": [{
        "managedPortfolio": "true",
        "slidingScaleFeeTier": [{
          "lowerBound": "0.00",
          "upperBound": "222222.00",
          "percentage": "2.00"
        }, {
          "lowerBound": "222222.00",
          "upperBound": "",
          "percentage": "4.00"
        }],
        "label": "Sliding scale fee component"
      }],
      "type": "Ongoing advice fee"
    },
    "licenseeFees": {
      "feesComponent": [{
        "listedSecurities": "0.00",
        "managedFund": "2.00",
        "managedPortfolio": "0.00",
        "termDeposit": "0.00",
        "cash": "0.00",
        "label": "Percentage fee component",
        "valid": false
      }],
      "type": "Licensee advice fee"
    }
  }
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/model/client_application_individual_crs_non_overseas.json
{
    "version": "1.0.0",
    "accountType": "individual",
    "investors": [
      {
        "displayTaxOptions": true,
        "cismandatory": true,
        "title": "MR",
        "firstname": "test",
        "middlename": "",
        "lastname": "one",
        "preferredname": "",
        "formername": "",
        "dateofbirth": "11\/11\/1990",
        "gender": "male",
        "mobile": {
          "value": ""
        },
        "email": {
          "value": ""
        },
        "preferredcontact": "",
        "isvalid": false,
        "accountType": "individual",
        "alternatename": "",
        "wealthsource": "Business income\/earnings",
        "sameasresaddress": "true",
        "taxdetails": {
        "ausTaxDetails": {
          "taxOption": {
            "value": "Tax File Number or exemption not provided",
            "valid": true
          },
          "exemptionReason": {
            "valid": true
          },
          "tfn": {
            "valid": false
          },
          "isTaxCountryAus": {
            "value": true,
            "valid": true
          }
        },
        "isOverseasTaxRes": {
          "value": false,
          "valid": true
        },
        "overseasTaxDetails": [{}
         
        ]
      },
        "identitydocument": {
          
        },
        "resaddressv2": {
          "country": "AU",
          "sameasaddress": "0",
          "addressType": "residential",
          "DisplayText": "",
          "valid": false
        },
        "postaladdressv2": {
          "country": "AU",
          "sameasaddress": "0",
          "addressType": "postal",
          "DisplayText": "",
          "valid": false
        },
        "taxcountry": "AU",
        "taxoption": ""
      }
    ],
    "accountsettings": {
      "investorAccountSettings": [
        {
          "hasRoles": false,
          "hasApprovers": false
        }
      ],
      "primarycontact": 0,
      "adviserName": "Edward Revis",
      "adviserLocation": "New South Wales"
    },
    "linkedaccounts": {
      "primaryLinkedAccount": {
        
      },
      "otherLinkedAccount": [
        
      ]
    },
    "fees": {
      "estamount": "0.00",
      "ongoingFees": {
        "feesComponent": [
          
        ],
        "type": "Ongoing advice fee"
      }
    }
	}
