=== Aim4dStars/work/nextgenx/src/main/resources/com/bt/nextgen/api/draftaccount/schemas/v1/directAccountApplicationSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "javaType" : "com.bt.nextgen.api.draftaccount.schemas.v1.DirectClientApplicationFormData",
  "type": "object",
  "properties": {
    "version": {
      "type": "string",
      "description": "this is the application Account JSON Schema Version number supported by client & server (http://semver.org/)",
      "pattern": "^[1-99]{1}.[0-99]{1}.[0-99]{1}$"
    },
    "accountType": {
      "$ref": "base/directAccountTypeEnum.json"
    },
    "pensioneligibility": {
      "type": "object",
      "$ref": "pensioneligibility/pensionEligibilitySchema.json",
      "description": "This schema is used for the Super Pension eligibility applicable only for super pension account."
    },
    "applicationOrigin" : {
      "$ref": "base/directApplicationOriginTypeEnum.json"
    },
    "adviceType" : {
      "$ref": "base/directAdviceTypeEnum.json"
    },
    "investors": {
      "type": "array",
      "items": {
        "$ref" : "customer/customerSchema.json"
      }
    },
    "linkedaccounts": {
      "$ref": "linkedaccounts/linkedAccountsApplicationSchema.json"
    },
    "investmentoptions": {
      "$ref": "investmentChoice/investmentChoiceSchema.json"
    }
  },
  "required": [
    "version",
    "investors"
  ],
  "additionalProperties": false
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/model/directIndividual_new_nonStandardAddr.json
{
  "version": "1.0.0",
  "applicationOrigin": "WestpacLive",
  "investors": [
    {
      "cisId": "1234567890",
      "userName": "21142019",
      "idVerified": true,
      "title": "MRS",
      "firstname": "DEEP",
      "lastname": "SHIKHA",
      "dateofbirth": "01\/01\/1989",
      "gender": "female",
      "email": {
        "value": "DS@DS.com"
      },
      "mobile": {
        "value": "5F109EF0B0E249E3FFD25A719026B90ACB691CF9D813BCCD"
      },
      "preferredcontact": "mobile",
      "resaddress": {
        "state": "NSW",
        "stateAbbr": "NSW",
        "city": "Sydney",
        "postcode": "2000",
        "country": "AU",
        "domicile": true,
        "mailingAddress": true,
        "addressType": "residential",
        "internationalAddress": false,
        "standardAddressFormat": false,
        "componentised": false,
        "addressLine1":"6/64 Gipps Street"
      },
      "postaladdress": {
        "state": "NSW",
        "stateAbbr": "NSW",
        "city": "Sydney",
        "postcode": "2000",
        "country": "AU",
        "domicile": true,
        "mailingAddress": true,
        "addressType": "residential",
        "internationalAddress": false,
        "standardAddressFormat": false,
        "componentised": false,
        "addressLine1":"6/64 Gipps Street"
      },
      "taxcountry": "AU",
      "taxoption": "Will provide Tax File Number later",
      "tfn": "",
      "exemptionreason": ""
    }
  ],
  "linkedaccounts": {
    "primaryLinkedAccount": {
      "accountname": "Westpac Choice",
      "bsb": "732006",
      "accountnumber": "750244",
      "bsbValidationResultVal": true
    },
    "otherLinkedAccount": [

    ]
  },
  "investmentoptions": {
    "portfolioType": "WFS0586AU",
    "initialDeposit": 42341241,
    "portfolioName": "BT Moderate Portfolio"
  }
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/builder/v3_JsonSchema/directIndividual_crsData.json
{
  "version": "1.0.0",
  "applicationOrigin": "WestpacLive",
  "investors": [
    {
      "cisId": "1234567892",
      "userName": "83916530",
      "idVerified": true,
      "title": "MR",
      "firstname": "SAURABH",
      "lastname": "BHARGAVA",
      "dateofbirth": "10/01/1992",
      "gender": "male",
      "preferredcontact": "mobile",
      "resaddress": {
        "unitNumber": "6",
        "floor": "55",
        "streetNumber": "45",
        "streetName": "Kent",
        "streetType": "St",
        "building": "Ece Arc",
        "suburb": "Sydney",
        "state": "NSW",
        "stateAbbr": "NSW",
        "city": "Sydney",
        "postcode": "2000",
        "country": "AU",
        "domicile": true,
        "mailingAddress": true,
        "addressType": "residential",
        "internationalAddress": false,
        "standardAddressFormat": true,
        "componentised": true,
        "pin": "2000"
      },
      "postaladdress": {
        "unitNumber": "6",
        "floor": "55",
        "streetNumber": "45",
        "streetName": "Kent",
        "streetType": "St",
        "building": "Ece Arc",
        "suburb": "Sydney",
        "state": "NSW",
        "stateAbbr": "NSW",
        "city": "Sydney",
        "postcode": "2000",
        "country": "AU",
        "domicile": true,
        "mailingAddress": true,
        "addressType": "residential",
        "internationalAddress": false,
        "standardAddressFormat": true,
        "componentised": true,
        "pin": "2000"
      },
      "email": {
        "value": "DS@DS.COM"
      },
      "mobile": {
        "value": "D5A37ED46E70AE3443CB5DC34E2377C22F90F04FA389EF991B19F243057129E6"
      },
      "taxdetails": {
        "ausTaxDetails": {
          "tfn": {},
          "taxOption": {
            "value": "Exemption Reason provided"
          },
          "exemptionReason": {
            "value": "norfolk_island_res"
          },
          "isTaxCountryAus": {
            "value": true
          }
        },
        "selectedOverseasTaxCountry": {
          "value": "AU"
        }
      }
    }
  ],
  "linkedaccounts": {
    "primaryLinkedAccount": {
      "accountname": "My Personal Account",
      "bsb": "732095",
      "accountnumber": "596137",
      "bsbValidationResultVal": true
    },
    "otherLinkedAccount": []
  }
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/model/individual-direct_noAccountTypePassed.json
{
  "version": "1.0.0",
  "applicationOrigin": "WestpacLive",
  "investors": [
    {
      "cisId": "432521525",
      "userName": "21142019",
      "idVerified": true,
      "title": "MRS",
      "firstname": "DEEP",
      "lastname": "SHIKHA",
      "dateofbirth": "01\/01\/1989",
      "gender": "female",
      "preferredcontact": "mobile",
      "resaddress": {
        "unitNumber": "9",
        "floor": "90",
        "streetNumber": "438",
        "streetName": "Market",
        "streetType": "St",
        "building": "Ece Arc",
        "suburb": "Sydney",
        "state": "NSW",
        "stateAbbr": "NSW",
        "city": "Sydney",
        "postcode": "2000",
        "country": "AU",
        "domicile": true,
        "mailingAddress": true,
        "addressType": "residential",
        "internationalAddress": false,
        "standardAddressFormat": true,
        "componentised": true,
        "pin": "2000"
      },
      "postaladdress": {
        "unitNumber": "9",
        "floor": "90",
        "streetNumber": "438",
        "streetName": "Market",
        "streetType": "St",
        "building": "Ece Arc",
        "suburb": "Sydney",
        "state": "NSW",
        "stateAbbr": "NSW",
        "city": "Sydney",
        "postcode": "2000",
        "country": "AU",
        "domicile": true,
        "mailingAddress": true,
        "addressType": "residential",
        "internationalAddress": false,
        "standardAddressFormat": true,
        "componentised": true,
        "pin": "2000"
      },
      "key": {
        "clientId": "13D4A6CA29708AFFAFB87974E54D27CFFB0EEA671252BEE7"
      }
    }
  ],
  "linkedaccounts": {
    "primaryLinkedAccount": {
      "accountname": "Westpac Choice",
      "bsb": "732006",
      "accountnumber": "750244",
      "bsbValidationResultVal": true
    },
    "otherLinkedAccount": [
    ]
  },
  "investmentoptions": {
    "portfolioType": "WFS0586AU",
    "initialDeposit": 42341241,
    "portfolioName": "BT Moderate Portfolio"
  }
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/model/individual-direct-superAccumulation.json
{
  "version": "1.0.0",
  "applicationOrigin": "WestpacLive",
  "accountType": "superAccumulation",
  "investors": [
    {
      "cisId": "57546320070",
      "userName": "75364576",
      "idVerified": true,
      "title": "MR",
      "firstname": "REGISTERONE",
      "lastname": "TEST",
      "dateofbirth": "05/02/1989",
      "gender": "male",
      "preferredcontact": "mobile",
      "resaddress": {
        "streetNumber": "33",
        "streetName": "Pitt Town",
        "streetType": "Rd",
        "suburb": "Kenthurst",
        "state": "NSW",
        "stateAbbr": "NSW",
        "city": "Kenthurst",
        "postcode": "2156",
        "country": "AU",
        "domicile": true,
        "mailingAddress": true,
        "addressType": "residential",
        "internationalAddress": false,
        "standardAddressFormat": true,
        "componentised": true,
        "pin": "2156"
      },
      "postaladdress": {
        "streetNumber": "33",
        "streetName": "Pitt Town",
        "streetType": "Rd",
        "suburb": "Kenthurst",
        "state": "NSW",
        "stateAbbr": "NSW",
        "city": "Kenthurst",
        "postcode": "2156",
        "country": "AU",
        "domicile": true,
        "mailingAddress": true,
        "addressType": "residential",
        "internationalAddress": false,
        "standardAddressFormat": true,
        "componentised": true,
        "pin": "2156"
      },
      "tfn": "11111111",
      "taxoption": "Tax File Number provided",
      "taxcountry": "AU",
      "key": {
        "clientId": "9055D5F318B9C6767627E539ADCEDAA7A6F4A52F926D4D6F"
      }
    }
  ]
}

=== Aim4dStars/work/nextgenx/src/test/resources/com/bt/nextgen/api/draftaccount/model/individual-direct-superPension.json
{
  "version": "1.0.0",
  "applicationOrigin": "WestpacLive",
  "accountType": "superPension",
  "pensioneligibility": {
    "conditionRelease": "OTH",
    "eligibilityCriteria": "UNPSV"
  },
  "investors": [
    {
      "cisId": "432521525",
      "userName": "21142019",
      "idVerified": true,
      "title": "MRS",
      "firstname": "DEEP",
      "lastname": "SHIKHA",
      "dateofbirth": "01\/01\/1989",
      "gender": "female",
      "preferredcontact": "mobile",
      "resaddress": {
        "unitNumber": "9",
        "floor": "90",
        "streetNumber": "438",
        "streetName": "Market",
        "streetType": "St",
        "building": "Ece Arc",
        "suburb": "Sydney",
        "state": "NSW",
        "stateAbbr": "NSW",
        "city": "Sydney",
        "postcode": "2000",
        "country": "AU",
        "domicile": true,
        "mailingAddress": true,
        "addressType": "residential",
        "internationalAddress": false,
        "standardAddressFormat": true,
        "componentised": true,
        "pin": "2000"
      },
      "postaladdress": {
        "unitNumber": "9",
        "floor": "90",
        "streetNumber": "438",
        "streetName": "Market",
        "streetType": "St",
        "building": "Ece Arc",
        "suburb": "Sydney",
        "state": "NSW",
        "stateAbbr": "NSW",
        "city": "Sydney",
        "postcode": "2000",
        "country": "AU",
        "domicile": true,
        "mailingAddress": true,
        "addressType": "residential",
        "internationalAddress": false,
        "standardAddressFormat": true,
        "componentised": true,
        "pin": "2000"
      },
      "tfn": "11111111",
      "taxoption": "Tax File Number provided",
      "taxcountry": "AU",
      "key": {
        "clientId": "13D4A6CA29708AFFAFB87974E54D27CFFB0EEA671252BEE7"
      }
    }
  ]
}
